### PR TITLE
Set custom map on element

### PR DESCRIPTION
**Pull request by cherifGsoul**

### CODE REVIEW

**Comment by cherifGsoul** [comment]
No problem!

**Comment by phillipskevin** [comment]
@cherifGsoul can you merge master into this to resolve the conflicts? Then I can merge and release both these changes.

**Comment by cherifGsoul** [comment]
@phillipskevin I doing it

**Comment by cherifGsoul** [comment]
@phillipskevin I fixed the conflicts

**Comment by phillipskevin** [comment]
Thanks @cherifGsoul. https://github.com/canjs/can-view-model/releases/tag/v3.2.0 is released.

**Pull request merged**
